import pandas as pd

# Load the original file
file_path = 'mmslangs.txt'
df = pd.read_csv(file_path, sep='\t', header=0)


# Create dictionaries for country and region information
language_info = {
    'abi': ('Ivory Coast', 'Africa'),
    'ace': ('Indonesia', 'Asia'),
    'aca': ('Colombia', 'South America'),
    'acn': ('China, Myanmar', 'Asia'),
    'acr': ('Guatemala', 'Central America'),
    'ach': ('Uganda, South Sudan', 'Africa'),
    'acu': ('Ecuador, Peru', 'South America'),
    'guq': ('Paraguay', 'South America'),
    'ade': ('Ghana, Togo', 'Africa'),
    'adj': ('Ivory Coast', 'Africa'),
    'agd': ('Papua New Guinea', 'Oceania'),
    'agx': ('Russia', 'Europe'),
    'agn': ('Philippines', 'Asia'),
    'aha': ('Ghana', 'Africa'),
    'aka': ('Ghana', 'Africa'),
    'knj': ('Guatemala', 'Central America'),
    'ake': ('Guyana, Venezuela', 'South America'),
    'aeu': ('Myanmar', 'Asia'),
    'ahk': ('China, Laos, Myanmar, Thailand', 'Asia'),
    'bss': ('Cameroon', 'Africa'),
    'alj': ('Philippines', 'Asia'),
    'sqi': ('Albania', 'Europe'),
    'alt': ('Russia', 'Asia'),
    'alp': ('Indonesia', 'Asia'),
    'alz': ('Uganda', 'Africa'),
    'kab': ('Algeria, Morocco', 'Africa'),
    'amk': ('Indonesia', 'Asia'),
    'mmg': ('Vanuatu', 'Oceania'),
    'amh': ('Ethiopia', 'Africa'),
    'ami': ('Taiwan', 'Asia'),
    'azg': ('Mexico', 'North America'),
    'agg': ('Papua New Guinea', 'Oceania'),
    'boj': ('Papua New Guinea', 'Oceania'),
    'cko': ('Ghana', 'Africa'),
    'any': ('Ivory Coast, Ghana', 'Africa'),
    'arl': ('Peru', 'South America'),
    'ara': ('Multiple Countries', 'Asia, Africa'),
    'atq': ('Indonesia', 'Asia'),
    'luc': ('Uganda', 'Africa'),
    'hyw': ('Turkey', 'Asia'),
    'apr': ('Papua New Guinea', 'Oceania'),
    'aia': ('Solomon Islands', 'Oceania'),
    'msy': ('Papua New Guinea', 'Oceania'),
    'cni': ('Peru', 'South America'),
    'cjo': ('Peru', 'South America'),
    'cpu': ('Peru', 'South America'),
    'cpb': ('Peru', 'South America'),
    'asm': ('India', 'Asia'),
    'asa': ('Tanzania', 'Africa'),
    'teo': ('Uganda, Kenya', 'Africa'),
    'ati': ('Ivory Coast', 'Africa'),
    'djk': ('Suriname', 'South America'),
    'ava': ('Russia', 'Europe'),
    'avn': ('Ghana', 'Africa'),
    'avu': ('South Sudan, Uganda', 'Africa'),
    'awb': ('Papua New Guinea', 'Oceania'),
    'kwi': ('Colombia, Ecuador', 'South America'),
    'awa': ('India', 'Asia'),
    'agr': ('Peru', 'South America'),
    'agu': ('Guatemala', 'Central America'),
    'ayr': ('Bolivia, Peru', 'South America'),
    'ayo': ('Bolivia, Paraguay', 'South America'),
    'abp': ('Philippines', 'Asia'),
    'blx': ('Philippines', 'Asia'),
    'sgb': ('Philippines', 'Asia'),
    'azj-script_cyrillic': ('Azerbaijan', 'Asia'),
    'azj-script_latin': ('Azerbaijan', 'Asia'),
    'azb': ('Iran', 'Asia'),
    'bba': ('Benin, Nigeria', 'Africa'),
    'bhz': ('Nigeria', 'Africa'),
    'bvc': ('Solomon Islands', 'Oceania'),
    'bfy': ('India', 'Asia'),
    'bgq': ('India', 'Asia'),
    'bdq': ('Vietnam', 'Asia'),
    'bdh': ('Cameroon', 'Africa'),
    'bqi': ('Iran', 'Asia'),
    'bjw': ('Ivory Coast', 'Africa'),
    'blz': ('Indonesia', 'Asia'),
    'ban': ('Indonesia', 'Asia'),
    'bcc-script_latin': ('Pakistan', 'Asia'),
    'bcc-script_arabic': ('Pakistan', 'Asia'),
    'bam': ('Mali', 'Africa'),
    'ptu': ('Indonesia', 'Asia'),
    'bcw': ('Nigeria', 'Africa'),
    'bqj': ('Senegal', 'Africa'),
    'bno': ('Philippines', 'Asia'),
    'bbb': ('Papua New Guinea', 'Oceania'),
    'bfa': ('South Sudan', 'Africa'),
    'bjz': ('Papua New Guinea', 'Oceania'),
    'bak': ('Russia', 'Europe'),
    'eus': ('Spain', 'Europe'),
    'bsq': ('Liberia, Sierra Leone', 'Africa'),
    'akb': ('Indonesia', 'Asia'),
    'btd': ('Indonesia', 'Asia'),
    'btx': ('Indonesia', 'Asia'),
    'bts': ('Indonesia', 'Asia'),
    'bbc': ('Indonesia', 'Asia'),
    'bvz': ('Indonesia', 'Asia'),
    'bjv': ('Central African Republic', 'Africa'),
    'bep': ('Indonesia', 'Asia'),
    'bkv': ('Nigeria', 'Africa'),
    'bzj': ('Belize', 'Central America'),
    'bem': ('Zambia', 'Africa'),
    'bng': ('Gabon', 'Africa'),
    'ben': ('India', 'Asia'),
    'bom': ('Nigeria', 'Africa'),
    'btt': ('Nigeria', 'Africa'),
    'bha': ('India', 'Asia'),
    'bgw': ('India', 'Asia'),
    'bht': ('India', 'Asia'),
    'beh': ('Benin', 'Africa'),
    'sne': ('Malaysia', 'Asia'),
    'ubl': ('Philippines', 'Asia'),
    'bcl': ('Philippines', 'Asia'),
    'bim': ('Ghana, Togo', 'Africa'),
    'bkd': ('Philippines', 'Asia'),
    'bjr': ('Papua New Guinea', 'Oceania'),
    'bfo': ('Burkina Faso', 'Africa'),
    'biv': ('Burkina Faso', 'Africa'),
    'bib': ('Zambia', 'Africa'),
    'bis': ('Vanuatu', 'Oceania'),
    'bzi': ('China', 'Asia'),
    'bqp': ('Burkina Faso', 'Africa'),
    'bpr': ('Philippines', 'Asia'),
    'bps': ('Philippines', 'Asia'),
    'bwq': ('Burkina Faso', 'Africa'),
    'bdv': ('India', 'Asia'),
    'bqc': ('Benin, Nigeria', 'Africa'),
    'bus': ('Nigeria', 'Africa'),
    'bnp': ('Papua New Guinea', 'Oceania'),
    'bmq': ('Mali', 'Africa'),
    'bdg': ('Malaysia', 'Asia'),
    'boa': ('Peru', 'South America'),
    'ksr': ('Papua New Guinea', 'Oceania'),
    'bor': ('Brazil', 'South America'),
    'bru': ('Laos', 'Asia'),
    'box': ('Burkina Faso', 'Africa'),
    'bzh': ('Papua New Guinea', 'Oceania'),
    'bgt': ('Solomon Islands', 'Oceania'),
    'sab': ('Panama', 'Central America'),
    'bul': ('Bulgaria', 'Europe'),
    'bwu': ('Ghana', 'Africa'),
    'bmv': ('Cameroon', 'Africa'),
    'mya': ('Myanmar', 'Asia'),
    'tte': ('Papua New Guinea', 'Oceania'),
    'cjp': ('Costa Rica', 'Central America'),
    'cbv': ('Colombia', 'South America'),
    'kaq': ('Peru', 'South America'),
    'cot': ('Peru', 'South America'),
    'cbc': ('Colombia', 'South America'),
    'car': ('Suriname', 'South America'),
    'cat': ('Spain', 'Europe'),
    'ceb': ('Philippines', 'Asia'),
    'cme': ('Burkina Faso', 'Africa'),
    'cbi': ('Ecuador', 'South America'),
    'ceg': ('Paraguay', 'South America'),
    'cly': ('Mexico', 'North America'),
    'cya': ('Mexico', 'North America'),
    'che': ('Russia', 'Europe'),
    'hne': ('India', 'Asia'),
    'nya': ('Malawi', 'Africa'),
    'dig': ('Kenya', 'Africa'),
    'dug': ('Tanzania', 'Africa'),
    'bgr': ('Myanmar', 'Asia'),
    'cek': ('Myanmar', 'Asia'),
    'cfm': ('Myanmar', 'Asia'),
    'cnh': ('Myanmar', 'Asia'),
    'hlt': ('Myanmar', 'Asia'),
    'mwq': ('Myanmar', 'Asia'),
    'ctd': ('Myanmar', 'Asia'),
    'tcz': ('Myanmar', 'Asia'),
    'zyp': ('Myanmar', 'Asia'),
    'cco': ('Mexico', 'North America'),
    'cnl': ('Mexico', 'North America'),
    'cle': ('Mexico', 'North America'),
    'chz': ('Mexico', 'North America'),
    'cpa': ('Mexico', 'North America'),
    'cso': ('Mexico', 'North America'),
    'cnt': ('Mexico', 'North America'),
    'cuc': ('Mexico', 'North America'),
    'hak': ('China', 'Asia'),
    'nan': ('China', 'Asia'),
    'xnj': ('Mozambique', 'Africa'),
    'cap': ('Bolivia', 'South America'),
    'cax': ('Bolivia', 'South America'),
    'ctg': ('Bangladesh', 'Asia'),
    'ctu': ('Mexico', 'North America'),
    'chf': ('Mexico', 'North America'),
    'cce': ('Mozambique', 'Africa'),
    'crt': ('Paraguay', 'South America'),
    'crq': ('Paraguay', 'South America'),
    'cac-dialect_sansebastiáncoatán': ('Guatemala', 'Central America'),
    'cac-dialect_sanmateoixtatán': ('Guatemala', 'Central America'),
    'ckt': ('Russia', 'Asia'),
    'ncu': ('Ghana', 'Africa'),
    'cdj': ('India', 'Asia'),
    'chv': ('Russia', 'Europe'),
    'caa': ('Guatemala', 'Central America'),
    'asg': ('Nigeria', 'Africa'),
    'con': ('Colombia', 'South America'),
    'crn': ('Mexico', 'North America'),
    'cok': ('Mexico', 'North America'),
    'crk-script_latin': ('Canada', 'North America'),
    'crk-script_syllabics': ('Canada', 'North America'),
    'crh': ('Ukraine', 'Europe'),
    'cui': ('Colombia', 'South America'),
    'dsh': ('Ethiopia', 'Africa'),
    'dbq': ('Cameroon', 'Africa'),
    'dga': ('Ghana', 'Africa'),
    'dgi': ('Ghana', 'Africa'),
    'dgk': ('Nigeria', 'Africa'),
    'dnj-dialect_gweetaawueast': ('Liberia', 'Africa'),
    'dnj-dialect_blowowest': ('Liberia', 'Africa'),
    'daa': ('Chad', 'Africa'),
    'dnt': ('Indonesia', 'Asia'),
    'dnw': ('Indonesia', 'Asia'),
    'dar': ('Russia', 'Europe'),
    'tcc': ('Tanzania', 'Africa'),
    'dwr': ('Ethiopia', 'Africa'),
    'ded': ('Papua New Guinea', 'Oceania'),
    'mzw': ('Chad', 'Africa'),
    'ntr': ('Nigeria', 'Africa'),
    'ddn': ('Benin', 'Africa'),
    'des': ('Colombia', 'South America'),
    'dso': ('India', 'Asia'),
    'nfa': ('Indonesia', 'Asia'),
    'dhi': ('Nepal', 'Asia'),
    'gud': ('Ivory Coast', 'Africa'),
    'did': ('South Sudan', 'Africa'),
    'mhu': ('India', 'Asia'),
    'dip': ('Sudan', 'Africa'),
    'dik': ('South Sudan', 'Africa'),
    'tbz': ('Benin', 'Africa'),
    'dts': ('Mali', 'Africa'),
    'dos': ('Burkina Faso', 'Africa'),
    'dgo': ('India', 'Asia'),
    'mvp': ('Indonesia', 'Asia'),
    'nld': ('Netherlands', 'Europe'),
    'jen': ('Nigeria', 'Africa'),
    'dzo': ('Bhutan', 'Asia'),
    'idd': ('Benin', 'Africa'),
    'eka': ('Nigeria', 'Africa'),
    'cto': ('Colombia', 'South America'),
    'emp': ('Colombia', 'South America'),
    'eng': ('United Kingdom', 'Europe'),
    'enx': ('Paraguay', 'South America'),
    'sja': ('Colombia', 'South America'),
    'myv': ('Russia', 'Europe'),
    'mcq': ('Nigeria', 'Africa'),
    'ese': ('Peru', 'South America'),
    'evn': ('Russia', 'Asia'),
    'eza': ('Nigeria', 'Africa'),
    'fal': ('Cameroon', 'Africa'),
    'fao': ('Faroe Islands', 'Europe'),
    'far': ('Solomon Islands', 'Oceania'),
    'fij': ('Fiji', 'Oceania'),
    'fin': ('Finland', 'Europe'),
    'fon': ('Benin', 'Africa'),
    'frd': ('Indonesia', 'Asia'),
    'fra': ('France', 'Europe'),
    'ful': ('Nigeria', 'Africa'),
    'flr': ('Congo', 'Africa'),
    'gau': ('India', 'Asia'),
    'gbk': ('India', 'Asia'),
    'gag-script_cyrillic': ('Moldova', 'Europe'),
    'gag-script_latin': ('Moldova', 'Europe'),
    'gbi': ('Indonesia', 'Asia'),
    'gmv': ('Ethiopia', 'Africa'),
    'lug': ('Uganda', 'Africa'),
    'pwg': ('Papua New Guinea', 'Oceania'),
    'gbm': ('India', 'Asia'),
    'cab': ('Honduras', 'Central America'),
    'grt': ('India', 'Asia'),
    'krs': ('Central African Republic', 'Africa'),
    'gso': ('Central African Republic', 'Africa'),
    'nlg': ('Solomon Islands', 'Oceania'),
    'gej': ('Ghana', 'Africa'),
    'deu': ('Germany', 'Europe'),
    'gri': ('Solomon Islands', 'Oceania'),
    'kik': ('Kenya', 'Africa'),
    'acd': ('Ghana', 'Africa'),
    'glk': ('Iran', 'Asia'),
    'gof-script_latin': ('Ethiopia', 'Africa'),
    'gog': ('Tanzania', 'Africa'),
    'gkn': ('Nigeria', 'Africa'),
    'wsg': ('India', 'Asia'),
    'gjn': ('Ghana', 'Africa'),
    'gqr': ('Papua New Guinea', 'Oceania'),
    'gor': ('Indonesia', 'Asia'),
    'gux': ('Burkina Faso', 'Africa'),
    'gbo': ('Liberia', 'Africa'),
    'ell': ('Greece', 'Europe'),
    'grc': ('Greece', 'Europe'),
    'guh': ('Colombia', 'South America'),
    'gub': ('Brazil', 'South America'),
    'grn': ('Paraguay', 'South America'),
    'gyr': ('Bolivia', 'South America'),
    'guo': ('Colombia', 'South America'),
    'gde': ('Nigeria', 'Africa'),
    'guj': ('India', 'Asia'),
    'gvl': ('Chad', 'Africa'),
    'guk': ('Ethiopia', 'Africa'),
    'rub': ('Uganda', 'Africa'),
    'dah': ('Ethiopia', 'Africa'),
    'gwr': ('Uganda', 'Africa'),
    'gwi': ('Canada', 'North America'),
    'hat': ('Haiti', 'North America'),
    'hlb': ('India', 'Asia'),
    'amf': ('Ethiopia', 'Africa'),
    'hag': ('Ghana', 'Africa'),
    'hnn': ('Philippines', 'Asia'),
    'bgc': ('India', 'Asia'),
    'had': ('Indonesia', 'Asia'),
    'hau': ('Nigeria', 'Africa'),
    'hwc': ('United States', 'North America'),
    'hvn': ('Indonesia', 'Asia'),
    'hay': ('Tanzania', 'Africa'),
    'xed': ('Cameroon', 'Africa'),
    'heb': ('Israel', 'Asia'),
    'heh': ('Tanzania', 'Africa'),
    'hil': ('Philippines', 'Asia'),
    'hin': ('India', 'Asia'),
    'hif': ('Fiji', 'Oceania'),
    'hns': ('Suriname', 'South America'),
    'hoc': ('India', 'Asia'),
    'hoy': ('India', 'Asia'),
    'hus-dialect_westernpotosino': ('Mexico', 'North America'),
    'hus-dialect_centralveracruz': ('Mexico', 'North America'),
    'huv': ('Mexico', 'North America'),
    'hui': ('Papua New Guinea', 'Oceania'),
    'hun': ('Hungary', 'Europe'),
    'hap': ('Indonesia', 'Asia'),
    'iba': ('Malaysia', 'Asia'),
    'isl': ('Iceland', 'Europe'),
    'dbj': ('Malaysia', 'Asia'),
    'ifa': ('Philippines', 'Asia'),
    'ifb': ('Philippines', 'Asia'),
    'ifu': ('Philippines', 'Asia'),
    'ifk': ('Philippines', 'Asia'),
    'ife': ('Togo', 'Africa'),
    'ign': ('Bolivia', 'South America'),
    'ikk': ('Colombia', 'South America'),
    'iqw': ('Nigeria', 'Africa'),
    'ilb': ('Zambia', 'Africa'),
    'ilo': ('Philippines', 'Asia'),
    'imo': ('Papua New Guinea', 'Oceania'),
    'ind': ('Indonesia', 'Asia'),
    'inb': ('Colombia', 'South America'),
    'ipi': ('Papua New Guinea', 'Oceania'),
    'irk': ('Tanzania', 'Africa'),
    'icr': ('Saint Kitts and Nevis', 'North America'),
    'itv': ('Philippines', 'Asia'),
    'itl': ('Russia', 'Asia'),
    'atg': ('Nigeria', 'Africa'),
    'ixl-dialect_sanjuancotzal': ('Guatemala', 'Central America'),
    'ixl-dialect_sangasparchajul': ('Guatemala', 'Central America'),
    'ixl-dialect_santamarianebaj': ('Guatemala', 'Central America'),
    'nca': ('Ecuador', 'South America'),
    'izr': ('Nigeria', 'Africa'),
    'izz': ('Nigeria', 'Africa'),
    'jac': ('Guatemala', 'Central America'),
    'jam': ('Jamaica', 'North America'),
    'jav': ('Indonesia', 'Asia'),
    'jvn': ('Suriname', 'South America'),
    'kac': ('Myanmar', 'Asia'),
    'dyo': ('Senegal', 'Africa'),
    'csk': ('Senegal', 'Africa'),
    'adh': ('Uganda', 'Africa'),
    'jun': ('India', 'Asia'),
    'jbu': ('Nigeria', 'Africa'),
    'dyu': ('Burkina Faso', 'Africa'),
    'bex': ('South Sudan', 'Africa'),
    'juy': ('Indonesia', 'Asia'),
    'gna': ('Burkina Faso', 'Africa'),
    'urb': ('Brazil', 'South America'),
    'kbp': ('Togo', 'Africa'),
    'cwa': ('Tanzania', 'Africa'),
    'dtp': ('Malaysia', 'Asia'),
    'kbr': ('Ethiopia', 'Africa'),
    'cgc': ('Philippines', 'Asia'),
    'kki': ('Tanzania', 'Africa'),
    'kzf': ('Indonesia', 'Asia'),
    'lew': ('Indonesia', 'Asia'),
    'cbr': ('Peru', 'South America'),
    'kkj': ('Cameroon', 'Africa'),
    'keo': ('South Sudan', 'Africa'),
    'kqe': ('Philippines', 'Asia'),
    'kak': ('Philippines', 'Asia'),
    'kyb': ('Philippines', 'Asia'),
    'knb': ('Philippines', 'Asia'),
    'kmd': ('Philippines', 'Asia'),
    'kml': ('Philippines', 'Asia'),
    'ify': ('Philippines', 'Asia'),
    'xal': ('Russia', 'Asia'),
    'kbq': ('Papua New Guinea', 'Oceania'),
    'kay': ('Brazil', 'South America'),
    'ktb': ('Ethiopia', 'Africa'),
    'hig': ('Nigeria', 'Africa'),
    'gam': ('Papua New Guinea', 'Oceania'),
    'cbu': ('Peru', 'South America'),
    'xnr': ('India', 'Asia'),
    'kmu': ('Papua New Guinea', 'Oceania'),
    'kne': ('Philippines', 'Asia'),
    'kan': ('India', 'Asia'),
    'kby': ('Nigeria', 'Africa'),
    'pam': ('Philippines', 'Asia'),
    'cak-dialect_santamaríadejesús': ('Guatemala', 'Central America'),
    'cak-dialect_southcentral': ('Guatemala', 'Central America'),
    'cak-dialect_yepocapa': ('Guatemala', 'Central America'),
    'cak-dialect_western': ('Guatemala', 'Central America'),
    'cak-dialect_santodomingoxenacoj': ('Guatemala', 'Central America'),
    'cak-dialect_central': ('Guatemala', 'Central America'),
    'xrb': ('Burkina Faso', 'Africa'),
    'krc': ('Russia', 'Europe'),
    'kaa': ('Uzbekistan', 'Asia'),
    'krl': ('Russia', 'Europe'),
    'pww': ('Myanmar', 'Asia'),
    'xsm': ('Ghana', 'Africa'),
    'cbs': ('Peru', 'South America'),
    'pss': ('Papua New Guinea', 'Oceania'),
    'kxf': ('Myanmar', 'Asia'),
    'kyz': ('Brazil', 'South America'),
    'kyu': ('Myanmar', 'Asia'),
    'txu': ('Brazil', 'South America'),
    'kaz': ('Kazakhstan', 'Asia'),
    'ndp': ('Togo', 'Africa'),
    'kbo': ('South Sudan', 'Africa'),
    'kyq': ('Chad', 'Africa'),
    'ken': ('Cameroon', 'Africa'),
    'ker': ('Chad', 'Africa'),
    'xte': ('Indonesia', 'Asia'),
    'kyg': ('Papua New Guinea', 'Oceania'),
    'kjh': ('Russia', 'Asia'),
    'kca': ('Russia', 'Europe'),
    'khm': ('Cambodia', 'Asia'),
    'kxm': ('Thailand', 'Asia'),
    'kjg': ('Laos', 'Asia'),
    'nyf': ('Kenya', 'Africa'),
    'kij': ('Papua New Guinea', 'Oceania'),
    'kia': ('Nigeria', 'Africa'),
    'kqr': ('Malaysia', 'Asia'),
    'kqp': ('Cameroon', 'Africa'),
    'krj': ('Philippines', 'Asia'),
    'zga': ('Tanzania', 'Africa'),
    'kin': ('Rwanda', 'Africa'),
    'pkb': ('Kenya', 'Africa'),
    'geb': ('Cameroon', 'Africa'),
    'gil': ('Kiribati', 'Oceania'),
    'kje': ('Indonesia', 'Asia'),
    'kss': ('Sierra Leone', 'Africa'),
    'thk': ('Kenya', 'Africa'),
    'klu': ('Liberia', 'Africa'),
    'kyo': ('Indonesia', 'Asia'),
    'kog': ('Colombia', 'South America'),
    'kfb': ('India', 'Asia'),
    'kpv': ('Russia', 'Europe'),
    'bbo': ('Burkina Faso', 'Africa'),
    'xon': ('Ghana', 'Africa'),
    'kma': ('Ghana', 'Africa'),
    'kno': ('Sierra Leone', 'Africa'),
    'kxc': ('Ethiopia', 'Africa'),
    'ozm': ('Cameroon', 'Africa'),
    'kqy': ('Ethiopia', 'Africa'),
    'kor': ('South Korea', 'Asia'),
    'coe': ('Colombia', 'South America'),
    'kpq': ('Indonesia', 'Asia'),
    'kpy': ('Russia', 'Asia'),
    'kyf': ('Ivory Coast', 'Africa'),
    'kff-script_telugu': ('India', 'Asia'),
    'kri': ('Sierra Leone', 'Africa'),
    'rop': ('Australia', 'Oceania'),
    'ktj': ('Ivory Coast', 'Africa'),
    'ted': ('Ivory Coast', 'Africa'),
    'krr': ('Cambodia', 'Asia'),
    'kdt': ('Laos', 'Asia'),
    'kez': ('Nigeria', 'Africa'),
    'cul': ('Brazil', 'South America'),
    'kle': ('Nepal', 'Asia'),
    'kdi': ('Uganda', 'Africa'),
    'kue': ('Papua New Guinea', 'Oceania'),
    'kum': ('Russia', 'Europe'),
    'kvn': ('Panama', 'Central America'),
    'cuk': ('Panama', 'Central America'),
    'kdn': ('Zambia', 'Africa'),
    'xuo': ('Ghana', 'Africa'),
    'key': ('India', 'Asia'),
    'kpz': ('Uganda', 'Africa'),
    'knk': ('Sierra Leone', 'Africa'),
    'kmr-script_latin': ('Turkey', 'Asia'),
    'kmr-script_arabic': ('Turkey', 'Asia'),
    'kmr-script_cyrillic': ('Turkey', 'Asia'),
    'xua': ('India', 'Asia'),
    'kru': ('India', 'Asia'),
    'kus': ('Ghana', 'Africa'),
    'kub': ('Nigeria', 'Africa'),
    'kdc': ('Tanzania', 'Africa'),
    'kxv': ('India', 'Asia'),
    'blh': ('Liberia', 'Africa'),
    'cwt': ('Senegal', 'Africa'),
    'kwd': ('Solomon Islands', 'Oceania'),
    'tnk': ('Vanuatu', 'Oceania'),
    'kwf': ('Solomon Islands', 'Oceania'),
    'cwe': ('Tanzania', 'Africa'),
    'kyc': ('Papua New Guinea', 'Oceania'),
    'tye': ('Nigeria', 'Africa'),
    'kir': ('Kyrgyzstan', 'Asia'),
    'quc-dialect_north': ('Guatemala', 'Central America'),
    'quc-dialect_east': ('Guatemala', 'Central America'),
    'quc-dialect_central': ('Guatemala', 'Central America'),
    'lac': ('Mexico', 'North America'),
    'lsi': ('Nigeria', 'Africa'),
    'lbj': ('India', 'Asia'),
    'lhu': ('China', 'Asia'),
    'las': ('Togo', 'Africa'),
    'lam': ('Zambia', 'Africa'),
    'lns': ('Cameroon', 'Africa'),
    'ljp': ('Indonesia', 'Asia'),
    'laj': ('Uganda', 'Africa'),
    'lao': ('Laos', 'Asia'),
    'lat': ('Vatican City', 'Europe'),
    'lav': ('Latvia', 'Europe'),
    'law': ('Indonesia', 'Asia'),
    'lcp': ('Thailand', 'Asia'),
    'lzz': ('Turkey', 'Asia'),
    'lln': ('Chad', 'Africa'),
    'lef': ('Ghana', 'Africa'),
    'acf': ('Saint Lucia', 'North America'),
    'lww': ('Vanuatu', 'Oceania'),
    'mhx': ('Nigeria', 'Africa'),
    'eip': ('Papua New Guinea', 'Oceania'),
    'lia': ('Sierra Leone', 'Africa'),
    'lif': ('Nepal', 'Asia'),
    'onb': ('China', 'Asia'),
    'lis': ('China', 'Asia'),
    'loq': ('Democratic Republic of the Congo', 'Africa'),
    'lob': ('Ivory Coast', 'Africa'),
    'yaz': ('Nigeria', 'Africa'),
    'lok': ('Sierra Leone', 'Africa'),
    'llg': ('Vanuatu', 'Oceania'),
    'ycl': ('China', 'Asia'),
    'lom': ('Liberia', 'Africa'),
    'ngl': ('Mozambique', 'Africa'),
    'lon': ('Malawi', 'Africa'),
    'lex': ('Indonesia', 'Asia'),
    'lgg': ('Uganda', 'Africa'),
    'ruf': ('Tanzania', 'Africa'),
    'dop': ('Benin', 'Africa'),
    'lnd': ('Malaysia', 'Asia'),
    'ndy': ('Tanzania', 'Africa'),
    'lwo': ('South Sudan', 'Africa'),
    'lee': ('Burkina Faso', 'Africa'),
    'mev': ('India', 'Asia'),
    'mfz': ('South Sudan', 'Africa'),
    'jmc': ('Tanzania', 'Africa'),
    'myy': ('Colombia', 'South America'),
    'mbc': ('Guyana', 'South America'),
    'mda': ('Nigeria', 'Africa'),
    'mad': ('Indonesia', 'Asia'),
    'mag': ('India', 'Asia'),
    'ayz': ('Indonesia', 'Asia'),
    'mai': ('India', 'Asia'),
    'mca': ('Paraguay', 'South America'),
    'mcp': ('Cameroon', 'Africa'),
    'mak': ('Indonesia', 'Asia'),
    'vmw': ('Mozambique', 'Africa'),
    'mgh': ('Mozambique', 'Africa'),
    'kde': ('Tanzania', 'Africa'),
    'mlg': ('Madagascar', 'Africa'),
    'zlm': ('Malaysia', 'Asia'),
    'pse': ('Indonesia', 'Asia'),
    'mkn': ('Indonesia', 'Asia'),
    'xmm': ('Indonesia', 'Asia'),
    'mal': ('India', 'Asia'),
    'xdy': ('Indonesia', 'Asia'),
    'div': ('Maldives', 'Asia'),
    'mdy': ('Ethiopia', 'Africa'),
    'mup': ('India', 'Asia'),
    'mam-dialect_central': ('Guatemala', 'Central America'),
    'mam-dialect_northern': ('Guatemala', 'Central America'),
    'mam-dialect_southern': ('Guatemala', 'Central America'),
    'mam-dialect_western': ('Guatemala', 'Central America'),
    'mqj': ('Indonesia', 'Asia'),
    'mcu': ('Cameroon', 'Africa'),
    'mzk': ('Nigeria', 'Africa'),
    'maw': ('Ghana', 'Africa'),
    'mjl': ('India', 'Asia'),
    'mnk': ('Senegal', 'Africa'),
    'mge': ('Papua New Guinea', 'Oceania'),
    'mbh': ('Papua New Guinea', 'Oceania'),
    'knf': ('Guinea-Bissau', 'Africa'),
    'mjv': ('India', 'Asia'),
    'mbt': ('Philippines', 'Asia'),
    'obo': ('Philippines', 'Asia'),
    'mbb': ('Philippines', 'Asia'),
    'mzj': ('Liberia', 'Africa'),
    'sjm': ('Philippines', 'Asia'),
    'mrw': ('Philippines', 'Asia'),
    'mar': ('India', 'Asia'),
    'mpg': ('Chad', 'Africa'),
    'mhr': ('Russia', 'Europe'),
    'enb': ('Kenya', 'Africa'),
    'mah': ('Marshall Islands', 'Oceania'),
    'myx': ('Uganda', 'Africa'),
    'klv': ('Vanuatu', 'Oceania'),
    'mfh': ('India', 'Asia'),
    'met': ('Papua New Guinea', 'Oceania'),
    'mcb': ('Peru', 'South America'),
    'mop': ('Belize', 'Central America'),
    'yua': ('Mexico', 'North America'),
    'mfy': ('Mexico', 'North America'),
    'maz': ('Mexico', 'North America'),
    'vmy': ('Mexico', 'North America'),
    'maq': ('Mexico', 'North America'),
    'mzi': ('Mexico', 'North America'),
    'maj': ('Mexico', 'North America'),
    'maa-dialect_sanantonio': ('Mexico', 'North America'),
    'maa-dialect_sanjerónimo': ('Mexico', 'North America'),
    'mhy': ('Indonesia', 'Asia'),
    'mhi': ('South Sudan', 'Africa'),
    'zmz': ('Central African Republic', 'Africa'),
    'myb': ('Chad', 'Africa'),
    'gai': ('Papua New Guinea', 'Oceania'),
    'mqb': ('Cameroon', 'Africa'),
    'mbu': ('Nigeria', 'Africa'),
    'med': ('Papua New Guinea', 'Oceania'),
    'men': ('Sierra Leone', 'Africa'),
    'mee': ('Papua New Guinea', 'Oceania'),
    'mwv': ('Indonesia', 'Asia'),
    'meq': ('Cameroon', 'Africa'),
    'zim': ('Nigeria', 'Africa'),
    'mgo': ('Cameroon', 'Africa'),
    'mej': ('Indonesia', 'Asia'),
    'mpp': ('Cameroon', 'Africa'),
    'min': ('Indonesia', 'Asia'),
    'gum': ('Colombia', 'South America'),
    'mpx': ('Papua New Guinea', 'Oceania'),
    'mco': ('Mexico', 'North America'),
    'mxq': ('Mexico', 'North America'),
    'pxm': ('Mexico', 'North America'),
    'mto': ('Mexico', 'North America'),
    'mim': ('Mexico', 'North America'),
    'xta': ('Mexico', 'North America'),
    'mbz': ('Mexico', 'North America'),
    'mip': ('Mexico', 'North America'),
    'mib': ('Mexico', 'North America'),
    'miy': ('Mexico', 'North America'),
    'mih': ('Mexico', 'North America'),
    'miz': ('Mexico', 'North America'),
    'xtd': ('Mexico', 'North America'),
    'mxt': ('Mexico', 'North America'),
    'xtm': ('Mexico', 'North America'),
    'mxv': ('Mexico', 'North America'),
    'xtn': ('Mexico', 'North America'),
    'mie': ('Mexico', 'North America'),
    'mil': ('Mexico', 'North America'),
    'mio': ('Mexico', 'North America'),
    'mdv': ('Mexico', 'North America'),
    'mza': ('Mexico', 'North America'),
    'mit': ('Mexico', 'North America'),
    'mxb': ('Mexico', 'North America'),
    'mpm': ('Mexico', 'North America'),
    'soy': ('Cameroon', 'Africa'),
    'cmo-script_latin': ('Vietnam', 'Asia'),
    'cmo-script_khmer': ('Vietnam', 'Asia'),
    'mfq': ('Ghana', 'Africa'),
    'old': ('Nigeria', 'Africa'),
    'mfk': ('Cameroon', 'Africa'),
    'mif': ('Cameroon', 'Africa'),
    'mkl': ('Guinea', 'Africa'),
    'mox': ('Papua New Guinea', 'Oceania'),
    'myl': ('Indonesia', 'Asia'),
    'mqf': ('Indonesia', 'Asia'),
    'mnw': ('Myanmar', 'Asia'),
    'mon': ('Mongolia', 'Asia'),
    'mog': ('Indonesia', 'Asia'),
    'mfe': ('Mauritius', 'Africa'),
    'mor': ('Sudan', 'Africa'),
    'mqn': ('Indonesia', 'Asia'),
    'mgd': ('South Sudan', 'Africa'),
    'mtj': ('Indonesia', 'Asia'),
    'cmr': ('Bangladesh', 'Asia'),
    'mtd': ('Indonesia', 'Asia'),
    'bmr': ('Colombia', 'South America'),
    'moz': ('Nigeria', 'Africa'),
    'mzm': ('Nigeria', 'Africa'),
    'mnb': ('Indonesia', 'Asia'),
    'mnf': ('Cameroon', 'Africa'),
    'unr': ('India', 'Asia'),
    'fmu': ('India', 'Asia'),
    'mur': ('South Sudan', 'Africa'),
    'tih': ('Malaysia', 'Asia'),
    'muv': ('India', 'Asia'),
    'muy': ('Cameroon', 'Africa'),
    'sur': ('Nigeria', 'Africa'),
    'moa': ('Congo', 'Africa'),
    'wmw': ('Mozambique', 'Africa'),
    'tnr': ('Nigeria', 'Africa'),
    'miq': ('Honduras', 'Central America'),
    'mos': ('Burkina Faso', 'Africa'),
    'muh': ('South Sudan', 'Africa'),
    'nas': ('Papua New Guinea', 'Oceania'),
    'mbj': ('Brazil', 'South America'),
    'nfr': ('Ghana', 'Africa'),
    'kfw': ('India', 'Asia'),
    'nst': ('Myanmar', 'Asia'),
    'nag': ('India', 'Asia'),
    'nch': ('Mexico', 'North America'),
    'nhe': ('Mexico', 'North America'),
    'ngu': ('Mexico', 'North America'),
    'azz': ('Mexico', 'North America'),
    'nhx': ('Mexico', 'North America'),
    'ncl': ('Mexico', 'North America'),
    'nhy': ('Mexico', 'North America'),
    'ncj': ('Mexico', 'North America'),
    'nsu': ('Mexico', 'North America'),
    'npl': ('Mexico', 'North America'),
    'nuz': ('Mexico', 'North America'),
    'nhw': ('Mexico', 'North America'),
    'nhi': ('Mexico', 'North America'),
    'nlc': ('Papua New Guinea', 'Oceania'),
    'nab': ('Brazil', 'South America'),
    'gld': ('Russia', 'Asia'),
    'nnb': ('Democratic Republic of the Congo', 'Africa'),
    'npy': ('Indonesia', 'Asia'),
    'pbb': ('Colombia', 'South America'),
    'ntm': ('Benin', 'Africa'),
    'nmz': ('Togo', 'Africa'),
    'naw': ('Ghana', 'Africa'),
    'nxq': ('China', 'Asia'),
    'ndj': ('Tanzania', 'Africa'),
    'ndz': ('South Sudan', 'Africa'),
    'ndv': ('Senegal', 'Africa'),
    'new': ('Nepal', 'Asia'),
    'nij': ('Indonesia', 'Asia'),
    'sba': ('Chad', 'Africa'),
    'gng': ('Cameroon', 'Africa'),
    'nga': ('Central African Republic', 'Africa'),
    'nnq': ('Tanzania', 'Africa'),
    'ngp': ('Tanzania', 'Africa'),
    'gym': ('Panama', 'Central America'),
    'kdj': ('Kenya', 'Africa'),
    'nia': ('Indonesia', 'Asia'),
    'nim': ('Tanzania', 'Africa'),
    'nin': ('Nigeria', 'Africa'),
    'nko': ('Ghana', 'Africa'),
    'nog': ('Russia', 'Asia'),
    'lem': ('Cameroon', 'Africa'),
    'not': ('Peru', 'South America'),
    'nhu': ('Ghana', 'Africa'),
    'bud': ('Ghana', 'Africa'),
    'nus': ('South Sudan', 'Africa'),
    'yas': ('Cameroon', 'Africa'),
    'nnw': ('Burkina Faso', 'Africa'),
    'nwb': ('Ivory Coast', 'Africa'),
    'nyy': ('Tanzania', 'Africa'),
    'nyn': ('Uganda', 'Africa'),
    'rim': ('Tanzania', 'Africa'),
    'lid': ('Papua New Guinea', 'Oceania'),
    'nuj': ('Uganda', 'Africa'),
    'nyo': ('Uganda', 'Africa'),
    'nzi': ('Ivory Coast', 'Africa'),
    'ann': ('Nigeria', 'Africa'),
    'ory': ('India', 'Asia'),
    'ojb-script_latin': ('Canada', 'North America'),
    'ojb-script_syllabics': ('Canada', 'North America'),
    'oku': ('Cameroon', 'Africa'),
    'bsc': ('Nigeria', 'Africa'),
    'bdu': ('Cameroon', 'Africa'),
    'orm': ('Ethiopia', 'Africa'),
    'ury': ('Papua New Guinea', 'Oceania'),
    'oss': ('Russia', 'Europe'),
    'ote': ('Mexico', 'North America'),
    'otq': ('Mexico', 'North America'),
    'stn': ('Solomon Islands', 'Oceania'),
    'sig': ('Ghana', 'Africa'),
    'kfx': ('India', 'Asia'),
    'bfz': ('India', 'Asia'),
    'sey': ('India', 'Asia'),
    'pao': ('United States', 'North America'),
    'pau': ('Palau', 'Oceania'),
    'pce': ('Myanmar', 'Asia'),
    'plw': ('Philippines', 'Asia'),
    'pmf': ('Indonesia', 'Asia'),
    'pag': ('Philippines', 'Asia'),
    'pap': ('Netherlands', 'Europe'),
    'prf': ('Philippines', 'Asia'),
    'pab': ('Brazil', 'South America'),
    'pbi': ('Cameroon', 'Africa'),
    'pbc': ('Guyana', 'South America'),
    'pad': ('Brazil', 'South America'),
    'ata': ('Papua New Guinea', 'Oceania'),
    'pez': ('Malaysia', 'Asia'),
    'peg': ('India', 'Asia'),
    'fas': ('Iran', 'Asia'),
    'pcm': ('Nigeria', 'Africa'),
    'pis': ('Solomon Islands', 'Oceania'),
    'pny': ('Cameroon', 'Africa'),
    'pir': ('Brazil', 'South America'),
    'pjt': ('Australia', 'Oceania'),
    'poy': ('Tanzania', 'Africa'),
    'pol': ('Poland', 'Europe'),
    'pps': ('Mexico', 'North America'),
    'pls': ('Mexico', 'North America'),
    'poi': ('Mexico', 'North America'),
    'poh-dialect_eastern': ('Guatemala', 'Central America'),
    'poh-dialect_western': ('Guatemala', 'Central America'),
    'por': ('Portugal', 'Europe'),
    'prt': ('Laos', 'Asia'),
    'pui': ('Colombia', 'South America'),
    'pan': ('India', 'Asia'),
    'tsz': ('Mexico', 'North America'),
    'suv': ('India', 'Asia'),
    'lme': ('Chad', 'Africa'),
    'quy': ('Peru', 'South America'),
    'qvc': ('Peru', 'South America'),
    'quz': ('Peru', 'South America'),
    'qve': ('Peru', 'South America'),
    'qub': ('Peru', 'South America'),
    'qvh': ('Peru', 'South America'),
    'qwh': ('Peru', 'South America'),
    'qvw': ('Peru', 'South America'),
    'quf': ('Peru', 'South America'),
    'qvm': ('Peru', 'South America'),
    'qul': ('Bolivia', 'South America'),
    'qvn': ('Peru', 'South America'),
    'qxn': ('Peru', 'South America'),
    'qxn': ('Peru', 'South America'),
    'qxh': ('Peru', 'South America'),
    'qvs': ('Peru', 'South America'),
    'quh': ('Bolivia', 'South America'),
    'qxo': ('Peru', 'South America'),
    'qxr': ('Ecuador', 'South America'),
    'qvo': ('Ecuador', 'South America'),
    'qvz': ('Ecuador', 'South America'),
    'qxl': ('Ecuador', 'South America'),
    'quw': ('Ecuador', 'South America'),
    'kjb': ('Guatemala', 'Central America'),
    'kek': ('Guatemala', 'Central America'),
    'rah': ('India', 'Asia'),
    'rjs': ('India', 'Asia'),
    'rai': ('Papua New Guinea', 'Oceania'),
    'lje': ('Indonesia', 'Asia'),
    'rnl': ('India', 'Asia'),
    'rkt': ('India', 'Asia'),
    'rap': ('Chile', 'South America'),
    'yea': ('India', 'Asia'),
    'raw': ('Myanmar', 'Asia'),
    'rej': ('Indonesia', 'Asia'),
    'rel': ('Kenya', 'Africa'),
    'ril': ('India', 'Asia'),
    'iri': ('Nigeria', 'Africa'),
    'rgu': ('Nigeria', 'Africa'),
    'rhg': ('Myanmar', 'Asia'),
    'rmc-script_latin': ('Ukraine', 'Europe'),
    'rmc-script_cyrillic': ('Ukraine', 'Europe'),
    'rmo': ('Germany', 'Europe'),
    'rmy-script_latin': ('Romania', 'Europe'),
    'rmy-script_cyrillic': ('Romania', 'Europe'),
    'ron': ('Romania', 'Europe'),
    'rol': ('Philippines', 'Asia'),
    'cla': ('Nigeria', 'Africa'),
    'rng': ('Mozambique', 'Africa'),
    'rug': ('Solomon Islands', 'Oceania'),
    'run': ('Burundi', 'Africa'),
    'rus': ('Russia', 'Europe'),
    'lsm': ('Tanzania', 'Africa'),
    'spy': ('Kenya', 'Africa'),
    'sck': ('India', 'Asia'),
    'saj': ('Indonesia', 'Asia'),
    'sch': ('India', 'Asia'),
    'sml': ('Philippines', 'Asia'),
    'xsb': ('Philippines', 'Asia'),
    'sbl': ('Philippines', 'Asia'),
    'saq': ('Kenya', 'Africa'),
    'sbd': ('Burkina Faso', 'Africa'),
    'smo': ('Samoa', 'Oceania'),
    'rav': ('Nepal', 'Asia'),
    'sxn': ('Indonesia', 'Asia'),
    'sag': ('Central African Republic', 'Africa'),
    'sbp': ('Tanzania', 'Africa'),
    'xsu': ('Venezuela', 'South America'),
    'srm': ('Suriname', 'South America'),
    'sas': ('Indonesia', 'Asia'),
    'apb': ('Solomon Islands', 'Oceania'),
    'sgw': ('Ethiopia', 'Africa'),
    'tvw': ('Indonesia', 'Asia'),
    'lip': ('Ghana', 'Africa'),
    'slu': ('Indonesia', 'Asia'),
    'snw': ('Ghana', 'Africa'),
    'sea': ('Malaysia', 'Asia'),
    'sza': ('Malaysia', 'Asia'),
    'seh': ('Mozambique', 'Africa'),
    'crs': ('Seychelles', 'Africa'),
    'ksb': ('Tanzania', 'Africa'),
    'shn': ('Myanmar', 'Asia'),
    'sho': ('Nigeria', 'Africa'),
    'mcd': ('Peru', 'South America'),
    'cbt': ('Peru', 'South America'),
    'xsr': ('Nepal', 'Asia'),
    'shk': ('South Sudan', 'Africa'),
    'shp': ('Peru', 'South America'),
    'sna': ('Zimbabwe', 'Africa'),
    'cjs': ('Russia', 'Asia'),
    'jiv': ('Ecuador', 'South America'),
    'snp': ('Papua New Guinea', 'Oceania'),
    'sya': ('India', 'Asia'),
    'sid': ('Ethiopia', 'Africa'),
    'snn': ('Colombia', 'South America'),
    'sri': ('Colombia', 'South America'),
    'srx': ('India', 'Asia'),
    'sil': ('Ghana', 'Africa'),
    'sld': ('Ghana', 'Africa'),
    'akp': ('Ghana', 'Africa'),
    'xog': ('Uganda', 'Africa'),
    'som': ('Somalia', 'Africa'),
    'bmu': ('Papua New Guinea', 'Oceania'),
    'khq': ('Mali', 'Africa'),
    'ses': ('Mali', 'Africa'),
    'mnx': ('Indonesia', 'Asia'),
    'spa': ('Spain', 'Europe'),
    'srn': ('Suriname', 'South America'),
    'sxb': ('Kenya', 'Africa'),
    'suc': ('Philippines', 'Asia'),
    'tgo': ('Papua New Guinea', 'Oceania'),
    'suk': ('Tanzania', 'Africa'),
    'sun': ('Indonesia', 'Asia'),
    'suz': ('Nepal', 'Asia'),
    'sgj': ('India', 'Asia'),
    'sus': ('Guinea', 'Africa'),
    'swh': ('Kenya', 'Africa'),
    'swe': ('Sweden', 'Europe'),
    'syl': ('Bangladesh', 'Asia'),
    'dyi': ('Ivory Coast', 'Africa'),
    'myk': ('Mali', 'Africa'),
    'spp': ('Mali', 'Africa'),
    'tap': ('Zambia', 'Africa'),
    'tby': ('Indonesia', 'Asia'),
    'tna': ('Bolivia', 'South America'),
    'shi': ('Morocco', 'Africa'),
    'klw': ('Indonesia', 'Asia'),
    'tgl': ('Philippines', 'Asia'),
    'tbk': ('Philippines', 'Asia'),
    'tgj': ('India', 'Asia'),
    'blt': ('Vietnam', 'Asia'),
    'tbg': ('Papua New Guinea', 'Oceania'),
    'omw': ('Papua New Guinea', 'Oceania'),
    'tgk': ('Tajikistan', 'Asia'),
    'tdj': ('Indonesia', 'Asia'),
    'tbc': ('Papua New Guinea', 'Oceania'),
    'tlj': ('Uganda', 'Africa'),
    'tly': ('Azerbaijan', 'Asia'),
    'ttq-script_tifinagh': ('Niger', 'Africa'),
    'taj': ('Nepal', 'Asia'),
    'taq': ('Mali', 'Africa'),
    'tam': ('India', 'Asia'),
    'tpm': ('Ghana', 'Africa'),
    'tgp': ('Vanuatu', 'Oceania'),
    'tnn': ('Vanuatu', 'Oceania'),
    'tac': ('Mexico', 'North America'),
    'rif-script_latin': ('Morocco', 'Africa'),
    'rif-script_arabic': ('Morocco', 'Africa'),
    'tat': ('Russia', 'Europe'),
    'tav': ('Colombia', 'South America'),
    'twb': ('Philippines', 'Asia'),
    'tbl': ('Philippines', 'Asia'),
    'kps': ('Indonesia', 'Asia'),
    'twe': ('Indonesia', 'Asia'),
    'ttc': ('Guatemala', 'Central America'),
    'tel': ('India', 'Asia'),
    'kdh': ('Togo', 'Africa'),
    'tes': ('Indonesia', 'Asia'),
    'tex': ('South Sudan', 'Africa'),
    'tee': ('Mexico', 'North America'),
    'tpp': ('Mexico', 'North America'),
    'tpt': ('Mexico', 'North America'),
    'stp': ('Mexico', 'North America'),
    'tfr': ('Costa Rica', 'Central America'),
    'twu': ('Indonesia', 'Asia'),
    'ter': ('Brazil', 'South America'),
    'tew': ('United States', 'North America'),
    'tha': ('Thailand', 'Asia'),
    'nod': ('Thailand', 'Asia'),
    'thl': ('India', 'Asia'),
    'tem': ('Sierra Leone', 'Africa'),
    'adx': ('China', 'Asia'),
    'bod': ('China', 'Asia'),
    'khg': ('China', 'Asia'),
    'tca': ('Brazil', 'South America'),
    'tir': ('Eritrea', 'Africa'),
    'txq': ('South Sudan', 'Africa'),
    'tik': ('Cameroon', 'Africa'),
    'dgr': ('Canada', 'North America'),
    'tob': ('Paraguay', 'South America'),
    'tmf': ('Paraguay', 'South America'),
    'qul': ('Bolivia', 'South America'),
    'qvn': ('Peru', 'South America'),
    'qxn': ('Peru', 'South America'),
    'qxh': ('Peru', 'South America'),
    'qvs': ('Peru', 'South America'),
    'quh': ('Bolivia', 'South America'),
    'qxo': ('Peru', 'South America'),
    'qxr': ('Ecuador', 'South America'),
    'qvo': ('Ecuador', 'South America'),
    'qvz': ('Ecuador', 'South America'),
    'qxl': ('Ecuador', 'South America'),
    'quw': ('Ecuador', 'South America'),
    'kjb': ('Guatemala', 'Central America'),
    'kek': ('Guatemala', 'Central America'),
    'rah': ('India', 'Asia'),
    'rjs': ('India', 'Asia'),
    'rai': ('Papua New Guinea', 'Oceania'),
    'lje': ('Indonesia', 'Asia'),
    'rnl': ('India', 'Asia'),
    'rkt': ('India', 'Asia'),
    'rap': ('Chile', 'South America'),
    'yea': ('India', 'Asia'),
    'raw': ('Myanmar', 'Asia'),
    'rej': ('Indonesia', 'Asia'),
    'rel': ('Kenya', 'Africa'),
    'ril': ('India', 'Asia'),
    'iri': ('Nigeria', 'Africa'),
    'rgu': ('Nigeria', 'Africa'),
    'rhg': ('Myanmar', 'Asia'),
    'rmc-script_latin': ('Ukraine', 'Europe'),
    'rmc-script_cyrillic': ('Ukraine', 'Europe'),
    'rmo': ('Germany', 'Europe'),
    'rmy-script_latin': ('Romania', 'Europe'),
    'rmy-script_cyrillic': ('Romania', 'Europe'),
    'ron': ('Romania', 'Europe'),
    'rol': ('Philippines', 'Asia'),
    'cla': ('Nigeria', 'Africa'),
    'rng': ('Mozambique', 'Africa'),
    'rug': ('Solomon Islands', 'Oceania'),
    'run': ('Burundi', 'Africa'),
    'rus': ('Russia', 'Europe'),
    'lsm': ('Tanzania', 'Africa'),
    'spy': ('Kenya', 'Africa'),
    'sck': ('India', 'Asia'),
    'saj': ('Indonesia', 'Asia'),
    'sch': ('India', 'Asia'),
    'sml': ('Philippines', 'Asia'),
    'xsb': ('Philippines', 'Asia'),
    'sbl': ('Philippines', 'Asia'),
    'saq': ('Kenya', 'Africa'),
    'sbd': ('Burkina Faso', 'Africa'),
    'smo': ('Samoa', 'Oceania'),
    'rav': ('Nepal', 'Asia'),
    'sxn': ('Indonesia', 'Asia'),
    'sag': ('Central African Republic', 'Africa'),
    'sbp': ('Tanzania', 'Africa'),
    'xsu': ('Venezuela', 'South America'),
    'srm': ('Suriname', 'South America'),
    'sas': ('Indonesia', 'Asia'),
    'apb': ('Solomon Islands', 'Oceania'),
    'sgw': ('Ethiopia', 'Africa'),
    'tvw': ('Indonesia', 'Asia'),
    'lip': ('Ghana', 'Africa'),
    'slu': ('Indonesia', 'Asia'),
    'snw': ('Ghana', 'Africa'),
    'sea': ('Malaysia', 'Asia'),
    'sza': ('Malaysia', 'Asia'),
    'seh': ('Mozambique', 'Africa'),
    'crs': ('Seychelles', 'Africa'),
    'ksb': ('Tanzania', 'Africa'),
    'shn': ('Myanmar', 'Asia'),
    'sho': ('Nigeria', 'Africa'),
    'mcd': ('Peru', 'South America'),
    'cbt': ('Peru', 'South America'),
    'xsr': ('Nepal', 'Asia'),
    'shk': ('South Sudan', 'Africa'),
    'shp': ('Peru', 'South America'),
    'sna': ('Zimbabwe', 'Africa'),
    'cjs': ('Russia', 'Asia'),
    'jiv': ('Ecuador', 'South America'),
    'snp': ('Papua New Guinea', 'Oceania'),
    'sya': ('India', 'Asia'),
    'sid': ('Ethiopia', 'Africa'),
    'snn': ('Colombia', 'South America'),
    'sri': ('Colombia', 'South America'),
    'srx': ('India', 'Asia'),
    'sil': ('Ghana', 'Africa'),
    'sld': ('Ghana', 'Africa'),
    'akp': ('Ghana', 'Africa'),
    'xog': ('Uganda', 'Africa'),
    'som': ('Somalia', 'Africa'),
    'bmu': ('Papua New Guinea', 'Oceania'),
    'khq': ('Mali', 'Africa'),
    'ses': ('Mali', 'Africa'),
    'mnx': ('Indonesia', 'Asia'),
    'spa': ('Spain', 'Europe'),
    'srn': ('Suriname', 'South America'),
    'sxb': ('Kenya', 'Africa'),
    'suc': ('Philippines', 'Asia'),
    'tgo': ('Papua New Guinea', 'Oceania'),
    'suk': ('Tanzania', 'Africa'),
    'sun': ('Indonesia', 'Asia'),
    'suz': ('Nepal', 'Asia'),
    'sgj': ('India', 'Asia'),
    'sus': ('Guinea', 'Africa'),
    'swh': ('Kenya', 'Africa'),
    'swe': ('Sweden', 'Europe'),
    'syl': ('Bangladesh', 'Asia'),
    'dyi': ('Ivory Coast', 'Africa'),
    'myk': ('Mali', 'Africa'),
    'spp': ('Mali', 'Africa'),
    'tap': ('Zambia', 'Africa'),
    'tby': ('Indonesia', 'Asia'),
    'tna': ('Bolivia', 'South America'),
    'shi': ('Morocco', 'Africa'),
    'klw': ('Indonesia', 'Asia'),
    'tgl': ('Philippines', 'Asia'),
    'tbk': ('Philippines', 'Asia'),
    'tgj': ('India', 'Asia'),
    'blt': ('Vietnam', 'Asia'),
    'tbg': ('Papua New Guinea', 'Oceania'),
    'omw': ('Papua New Guinea', 'Oceania'),
    'tgk': ('Tajikistan', 'Asia'),
    'tdj': ('Indonesia', 'Asia'),
    'tbc': ('Papua New Guinea', 'Oceania'),
    'tlj': ('Uganda', 'Africa'),
    'tly': ('Azerbaijan', 'Asia'),
    'ttq-script_tifinagh': ('Niger', 'Africa'),
    'taj': ('Nepal', 'Asia'),
    'taq': ('Mali', 'Africa'),
    'tam': ('India', 'Asia'),
    'tpm': ('Ghana', 'Africa'),
    'tgp': ('Vanuatu', 'Oceania'),
    'tnn': ('Vanuatu', 'Oceania'),
    'tac': ('Mexico', 'North America'),
    'rif-script_latin': ('Morocco', 'Africa'),
    'rif-script_arabic': ('Morocco', 'Africa'),
    'tat': ('Russia', 'Europe'),
    'tav': ('Colombia', 'South America'),
    'twb': ('Philippines', 'Asia'),
    'tbl': ('Philippines', 'Asia'),
    'kps': ('Indonesia', 'Asia'),
    'twe': ('Indonesia', 'Asia'),
    'ttc': ('Guatemala', 'Central America'),
    'tel': ('India', 'Asia'),
    'kdh': ('Togo', 'Africa'),
    'tes': ('Indonesia', 'Asia'),
    'tex': ('South Sudan', 'Africa'),
    'tee': ('Mexico', 'North America'),
    'tpp': ('Mexico', 'North America'),
    'tpt': ('Mexico', 'North America'),
    'stp': ('Mexico', 'North America'),
    'tfr': ('Costa Rica', 'Central America'),
    'twu': ('Indonesia', 'Asia'),
    'ter': ('Brazil', 'South America'),
    'tew': ('United States', 'North America'),
    'tha': ('Thailand', 'Asia'),
    'nod': ('Thailand', 'Asia'),
    'thl': ('India', 'Asia'),
    'tem': ('Sierra Leone', 'Africa'),
    'adx': ('China', 'Asia'),
    'bod': ('China', 'Asia'),
    'khg': ('China', 'Asia'),
    'tca': ('Brazil', 'South America'),
    'tir': ('Eritrea', 'Africa'),
    'txq': ('South Sudan', 'Africa'),
    'tik': ('Cameroon', 'Africa'),
    'dgr': ('Canada', 'North America'),
    'mie': ('Mexico', 'North America'),
    'mil': ('Mexico', 'North America'),
    'mio': ('Mexico', 'North America'),
    'mdv': ('Mexico', 'North America'),
    'mza': ('Mexico', 'North America'),
    'mit': ('Mexico', 'North America'),
    'mxb': ('Mexico', 'North America'),
    'mpm': ('Mexico', 'North America'),
    'soy': ('Cameroon', 'Africa'),
    'cmo-script_latin': ('Vietnam', 'Asia'),
    'cmo-script_khmer': ('Vietnam', 'Asia'),
    'mfq': ('Ghana', 'Africa'),
    'old': ('Nigeria', 'Africa'),
    'mfk': ('Cameroon', 'Africa'),
    'mif': ('Cameroon', 'Africa'),
    'mkl': ('Guinea', 'Africa'),
    'mox': ('Papua New Guinea', 'Oceania'),
    'myl': ('Indonesia', 'Asia'),
    'mqf': ('Indonesia', 'Asia'),
    'mnw': ('Myanmar', 'Asia'),
    'mon': ('Mongolia', 'Asia'),
    'mog': ('Indonesia', 'Asia'),
    'mfe': ('Mauritius', 'Africa'),
    'mor': ('Sudan', 'Africa'),
    'mqn': ('Indonesia', 'Asia'),
    'mgd': ('South Sudan', 'Africa'),
    'mtj': ('Indonesia', 'Asia'),
    'cmr': ('Bangladesh', 'Asia'),
    'mtd': ('Indonesia', 'Asia'),
    'bmr': ('Colombia', 'South America'),
    'moz': ('Nigeria', 'Africa'),
    'mzm': ('Nigeria', 'Africa'),
    'mnb': ('Indonesia', 'Asia'),
    'mnf': ('Cameroon', 'Africa'),
    'unr': ('India', 'Asia'),
    'fmu': ('India', 'Asia'),
    'mur': ('South Sudan', 'Africa'),
    'tih': ('Malaysia', 'Asia'),
    'muv': ('India', 'Asia'),
    'muy': ('Cameroon', 'Africa'),
    'sur': ('Nigeria', 'Africa'),
    'moa': ('Congo', 'Africa'),
    'wmw': ('Mozambique', 'Africa'),
    'tnr': ('Nigeria', 'Africa'),
    'miq': ('Honduras', 'Central America'),
    'mos': ('Burkina Faso', 'Africa'),
    'muh': ('South Sudan', 'Africa'),
    'nas': ('Papua New Guinea', 'Oceania'),
    'mbj': ('Brazil', 'South America'),
    'nfr': ('Ghana', 'Africa'),
    'kfw': ('India', 'Asia'),
    'nst': ('Myanmar', 'Asia'),
    'nag': ('India', 'Asia'),
    'nch': ('Mexico', 'North America'),
    'nhe': ('Mexico', 'North America'),
    'ngu': ('Mexico', 'North America'),
    'azz': ('Mexico', 'North America'),
    'nhx': ('Mexico', 'North America'),
    'ncl': ('Mexico', 'North America'),
    'nhy': ('Mexico', 'North America'),
    'ncj': ('Mexico', 'North America'),
    'nsu': ('Mexico', 'North America'),
    'npl': ('Mexico', 'North America'),
    'nuz': ('Mexico', 'North America'),
    'nhw': ('Mexico', 'North America'),
    'nhi': ('Mexico', 'North America'),
    'nlc': ('Papua New Guinea', 'Oceania'),
    'nab': ('Brazil', 'South America'),
    'gld': ('Russia', 'Asia'),
    'nnb': ('Democratic Republic of the Congo', 'Africa'),
    'npy': ('Indonesia', 'Asia'),
    'pbb': ('Colombia', 'South America'),
    'ntm': ('Benin', 'Africa'),
    'nmz': ('Togo', 'Africa'),
    'naw': ('Ghana', 'Africa'),
    'nxq': ('China', 'Asia'),
    'ndj': ('Tanzania', 'Africa'),
    'ndz': ('South Sudan', 'Africa'),
    'ndv': ('Senegal', 'Africa'),
    'new': ('Nepal', 'Asia'),
    'nij': ('Indonesia', 'Asia'),
    'sba': ('Chad', 'Africa'),
    'gng': ('Cameroon', 'Africa'),
    'nga': ('Central African Republic', 'Africa'),
    'nnq': ('Tanzania', 'Africa'),
    'ngp': ('Tanzania', 'Africa'),
    'gym': ('Panama', 'Central America'),
    'kdj': ('Kenya', 'Africa'),
    'nia': ('Indonesia', 'Asia'),
    'nim': ('Tanzania', 'Africa'),
    'nin': ('Nigeria', 'Africa'),
    'nko': ('Ghana', 'Africa'),
    'nog': ('Russia', 'Asia'),
    'lem': ('Cameroon', 'Africa'),
    'not': ('Peru', 'South America'),
    'nhu': ('Ghana', 'Africa'),
    'bud': ('Ghana', 'Africa'),
    'nus': ('South Sudan', 'Africa'),
    'yas': ('Cameroon', 'Africa'),
    'nnw': ('Burkina Faso', 'Africa'),
    'nwb': ('Ivory Coast', 'Africa'),
    'nyy': ('Tanzania', 'Africa'),
    'nyn': ('Uganda', 'Africa'),
    'rim': ('Tanzania', 'Africa'),
    'lid': ('Papua New Guinea', 'Oceania'),
    'nuj': ('Uganda', 'Africa'),
    'nyo': ('Uganda', 'Africa'),
    'nzi': ('Ivory Coast', 'Africa'),
    'ann': ('Nigeria', 'Africa'),
    'ory': ('India', 'Asia'),
    'ojb-script_latin': ('Canada', 'North America'),
    'ojb-script_syllabics': ('Canada', 'North America'),
    'oku': ('Cameroon', 'Africa'),
    'bsc': ('Nigeria', 'Africa'),
    'bdu': ('Cameroon', 'Africa'),
    'orm': ('Ethiopia', 'Africa'),
    'ury': ('Papua New Guinea', 'Oceania'),
    'oss': ('Russia', 'Europe'),
    'ote': ('Mexico', 'North America'),
    'otq': ('Mexico', 'North America'),
    'stn': ('Solomon Islands', 'Oceania'),
    'sig': ('Ghana', 'Africa'),
    'kfx': ('India', 'Asia'),
    'bfz': ('India', 'Asia'),
    'sey': ('India', 'Asia'),
    'pao': ('United States', 'North America'),
    'pau': ('Palau', 'Oceania'),
    'pce': ('Myanmar', 'Asia'),
    'plw': ('Philippines', 'Asia'),
    'pmf': ('Indonesia', 'Asia'),
    'pag': ('Philippines', 'Asia'),
    'pap': ('Netherlands', 'Europe'),
    'prf': ('Philippines', 'Asia'),
    'pab': ('Brazil', 'South America'),
    'pbi': ('Cameroon', 'Africa'),
    'pbc': ('Guyana', 'South America'),
    'pad': ('Brazil', 'South America'),
    'ata': ('Papua New Guinea', 'Oceania'),
    'pez': ('Malaysia', 'Asia'),
    'peg': ('India', 'Asia'),
    'fas': ('Iran', 'Asia'),
    'pcm': ('Nigeria', 'Africa'),
    'pis': ('Solomon Islands', 'Oceania'),
    'pny': ('Cameroon', 'Africa'),
    'pir': ('Brazil', 'South America'),
    'pjt': ('Australia', 'Oceania'),
    'poy': ('Tanzania', 'Africa'),
    'pol': ('Poland', 'Europe'),
    'pps': ('Mexico', 'North America'),
    'pls': ('Mexico', 'North America'),
    'poi': ('Mexico', 'North America'),
    'poh-dialect_eastern': ('Guatemala', 'Central America'),
    'poh-dialect_western': ('Guatemala', 'Central America'),
    'por': ('Portugal', 'Europe'),
    'prt': ('Laos', 'Asia'),
    'pui': ('Colombia', 'South America'),
    'pan': ('India', 'Asia'),
    'tsz': ('Mexico', 'North America'),
    'suv': ('India', 'Asia'),
    'lme': ('Chad', 'Africa'),
    'quy': ('Peru', 'South America'),
    'qvc': ('Peru', 'South America'),
    'quz': ('Peru', 'South America'),
    'qve': ('Peru', 'South America'),
    'qub': ('Peru', 'South America'),
    'qvh': ('Peru', 'South America'),
    'qwh': ('Peru', 'South America'),
    'qvw': ('Peru', 'South America'),
    'quf': ('Peru', 'South America'),
    'qvm': ('Peru', 'South America'),
    'tob': ('Argentina', 'South America'),
    'tmf': ('Paraguay', 'South America'),
    'tng': ('Papua New Guinea', 'Oceania'),
    'tlb': ('Indonesia', 'Asia'),
    'ood': ('United States', 'North America'),
    'tpi': ('Papua New Guinea', 'Oceania'),
    'jic': ('Honduras', 'Central America'),
    'lbw': ('Indonesia', 'Asia'),
    'txa': ('Malaysia', 'Asia'),
    'tom': ('Indonesia', 'Asia'),
    'toh': ('Zambia', 'Africa'),
    'tnt': ('Indonesia', 'Asia'),
    'sda': ('Indonesia', 'Asia'),
    'tcs': ('Australia', 'Oceania'),
    'toc': ('Mexico', 'North America'),
    'tos': ('Mexico', 'North America'),
    'neb': ('Ivory Coast', 'Africa'),
    'trn': ('Bolivia', 'South America'),
    'trs': ('Mexico', 'North America'),
    'trc': ('Mexico', 'North America'),
    'tri': ('Brazil', 'South America'),
    'cof': ('Ecuador', 'South America'),
    'tkr': ('Azerbaijan', 'Asia'),
    'kdl': ('Nigeria', 'Africa'),
    'cas': ('Bolivia', 'South America'),
    'tso': ('Mozambique', 'Africa'),
    'tuo': ('Colombia', 'South America'),
    'iou': ('Indonesia', 'Asia'),
    'tmc': ('Chad', 'Africa'),
    'tuf': ('Colombia', 'South America'),
    'tur': ('Turkey', 'Asia'),
    'tuk-script_latin': ('Turkmenistan', 'Asia'),
    'tuk-script_arabic': ('Turkmenistan', 'Asia'),
    'bov': ('Ghana', 'Africa'),
    'tue': ('Colombia', 'South America'),
    'kcg': ('Nigeria', 'Africa'),
    'tzh-dialect_bachajón': ('Mexico', 'North America'),
    'tzh-dialect_tenejapa': ('Mexico', 'North America'),
    'tzo-dialect_chenalhó': ('Mexico', 'North America'),
    'tzo-dialect_chamula': ('Mexico', 'North America'),
    'tzj-dialect_western': ('Guatemala', 'Central America'),
    'tzj-dialect_eastern': ('Guatemala', 'Central America'),
    'aoz': ('East Timor', 'Asia'),
    'udm': ('Russia', 'Europe'),
    'udu': ('South Sudan', 'Africa'),
    'ukr': ('Ukraine', 'Europe'),
    'ppk': ('Indonesia', 'Asia'),
    'ubu': ('Papua New Guinea', 'Oceania'),
    'urk': ('Thailand', 'Asia'),
    'ura': ('Peru', 'South America'),
    'urt': ('Papua New Guinea', 'Oceania'),
    'urd-script_devanagari': ('India', 'Asia'),
    'urd-script_arabic': ('India', 'Asia'),
    'urd-script_latin': ('India', 'Asia'),
    'upv': ('Vanuatu', 'Oceania'),
    'usp': ('Guatemala', 'Central America'),
    'uig-script_arabic': ('China', 'Asia'),
    'uig-script_cyrillic': ('China', 'Asia'),
    'uzb-script_cyrillic': ('Uzbekistan', 'Asia'),
    'vag': ('Ghana', 'Africa'),
    'bav': ('Cameroon', 'Africa'),
    'vid': ('Tanzania', 'Africa'),
    'vie': ('Vietnam', 'Asia'),
    'vif': ('Gabon', 'Africa'),
    'vun': ('Tanzania', 'Africa'),
    'vut': ('Cameroon', 'Africa'),
    'prk': ('Myanmar', 'Asia'),
    'wwa': ('Ghana', 'Africa'),
    'rro': ('Papua New Guinea', 'Oceania'),
    'bao': ('Colombia', 'South America'),
    'waw': ('Brazil', 'South America'),
    'lgl': ('Vanuatu', 'Oceania'),
    'wlx': ('Ghana', 'Africa'),
    'cou': ('Guinea', 'Africa'),
    'hub': ('Ecuador', 'South America'),
    'gvc': ('Colombia', 'South America'),
    'mfi': ('Nigeria', 'Africa'),
    'wap': ('Guyana', 'South America'),
    'wba': ('Guyana', 'South America'),
    'war': ('Philippines', 'Asia'),
    'way': ('Suriname', 'South America'),
    'guc': ('Colombia', 'South America'),
    'cym': ('United Kingdom', 'Europe'),
    'kvw': ('Indonesia', 'Asia'),
    'tnp': ('Vanuatu', 'Oceania'),
    'hto': ('Peru', 'South America'),
    'huu': ('Colombia', 'South America'),
    'wal-script_latin': ('Ethiopia', 'Africa'),
    'wal-script_ethiopic': ('Ethiopia', 'Africa'),
    'wlo': ('Indonesia', 'Asia'),
    'noa': ('Panama', 'Central America'),
    'wob': ('Ivory Coast', 'Africa'),
    'kao': ('Mali', 'Africa'),
    'xer': ('Brazil', 'South America'),
    'yad': ('Peru', 'South America'),
    'yka': ('Philippines', 'Asia'),
    'sah': ('Russia', 'Asia'),
    'yba': ('Nigeria', 'Africa'),
    'yli': ('Indonesia', 'Asia'),
    'nlk': ('Indonesia', 'Asia'),
    'yal': ('Guinea', 'Africa'),
    'yam': ('Nigeria', 'Africa'),
    'yat': ('Cameroon', 'Africa'),
    'jmd': ('Indonesia', 'Asia'),
    'tao': ('Philippines', 'Asia'),
    'yaa': ('Peru', 'South America'),
    'ame': ('Peru', 'South America'),
    'guu': ('Brazil', 'South America'),
    'yao': ('Mozambique', 'Africa'),
    'yre': ('Ivory Coast', 'Africa'),
    'yva': ('Indonesia', 'Asia'),
    'ybb': ('Cameroon', 'Africa'),
    'pib': ('Peru', 'South America'),
    'byr': ('Papua New Guinea', 'Oceania'),
    'pil': ('Togo', 'Africa'),
    'yor': ('Nigeria', 'Africa'),
    'ycn': ('Colombia', 'South America'),
    'ess': ('United States', 'North America'),
    'yuz': ('Bolivia', 'South America'),
    'atb': ('China', 'Asia'),
    'zne': ('Democratic Republic of the Congo', 'Africa'),
    'zaq': ('Mexico', 'North America'),
    'zpo': ('Mexico', 'North America'),
    'zad': ('Mexico', 'North America'),
    'zpc': ('Mexico', 'North America'),
    'zca': ('Mexico', 'North America'),
    'zpg': ('Mexico', 'North America'),
    'zai': ('Mexico', 'North America'),
    'zpl': ('Mexico', 'North America'),
    'zam': ('Mexico', 'North America'),
    'zaw': ('Mexico', 'North America'),
    'zpm': ('Mexico', 'North America'),
    'zac': ('Mexico', 'North America'),
    'zao': ('Mexico', 'North America'),
    'ztq': ('Mexico', 'North America'),
    'zar': ('Mexico', 'North America'),
    'zpt': ('Mexico', 'North America'),
    'zpi': ('Mexico', 'North America'),
    'zas': ('Mexico', 'North America'),
    'zaa': ('Mexico', 'North America'),
    'zpz': ('Mexico', 'North America'),
    'zab': ('Mexico', 'North America'),
    'zpu': ('Mexico', 'North America'),
    'zae': ('Mexico', 'North America'),
    'zty': ('Mexico', 'North America'),
    'zav': ('Mexico', 'North America'),
    'zza': ('Turkey', 'Asia'),
    'zyb': ('China', 'Asia'),
    'ziw': ('Tanzania', 'Africa'),
    'zos': ('Mexico', 'North America'),
    'gnd': ('Cameroon', 'Africa'),
    'ewe': ('Ghana', 'Africa')
}
# Map the dictionary to extract country and region data
df['Country'] = df['Iso Code'].map(lambda code: language_info.get(code, ('Unknown', 'Unknown'))[0])
df['Region'] = df['Iso Code'].map(lambda code: language_info.get(code, ('Unknown', 'Unknown'))[1])

# Save the updated dataframe to a new file
output_path = 'mmslangs_updated.txt'  # Replace with your actual output file path
df.to_csv(output_path, sep='\t', index=False)

print("File updated and saved successfully.")
